### ISSUE TITLE
Merged code from the Xiaomi kernel is not enabled in charging driver.

### ISSUE THREAD

**Issue by samikhawaja** [blankaf/kernel_xiaomi_msm8998#1]
Following commit merges the power changes but does not enable the define used in the qpnp-smb2.c

In @Demon000 's repository the Kconfig and kernel config changes are correct and the define is enabled. But these changes are not merged. 

Due to this the battery is charged with more current as compared to the current ratings set in Xiaomi released kernel source. This makes the device heat up when charging. Also the charger heats up because device draws more current from the charger.

` drivers: power: import xiaomi changes

* import voltage limits
* enable try sink mode
* wait more for typec detection
* do device wakeup before smb probe logic

Change-Id: I3dfd28cd005c03e7001fa51fe1df332e4d330236`

Best Regards

**Comment by blankaf** [comment]
Oh God, I didn't know that I screwed up that. I have imported the changes from the Oreo OSS kernel now.
https://github.com/blankaf/kernel_xiaomi_msm8998/commit/77a759806fbeee14695c40e92792e029151137ff

Thanks!

**Comment by samikhawaja** [comment]
We all mess up things!

I noticed this and commented on the xda thread, but didn't see any update on github in your repo so thought maybe create an issue here.

Other than this your ROM is in very good shape I think.

**Comment by blankaf** [comment]
Alright! :+1: 
I'll release an update on xda soon.
