### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by samikhawaja** [blankaf/kernel_xiaomi_msm8998#3]
Hi,

Could you please tell me how I can build this ROM? I mean is there any difference between building a treble ROM and a non-treble rom?

My local_manifests roomservice file contents are attached, can you please check whether these are the correct branches to build your treble ROM?

Thanks.

**Comment by blankaf** [comment]
@samikhawaja NO U

**Comment by samikhawaja** [comment]
[roomservice.txt](https://github.com/blankaf/kernel_xiaomi_msm8998/files/1864202/roomservice.txt)

**Comment by samikhawaja** [comment]
Sorry but I didn't get your reply.

Thanks

**Comment by saxmydix** [comment]
What is NO U?? We don't get it?!

**Comment by p8tgames** [comment]
Idk either What No U means...
We will never know...

**Comment by saxmydix** [comment]
The question is why is it in CAPITAL letter??

**Comment by p8tgames** [comment]
I dont KNOW either man.

**Comment by saxmydix** [comment]
I don't know but it looks like he's being RUDE?!

**Comment by blankaf** [comment]
@saxmydix Lol

**Comment by p8tgames** [comment]
@saxmydix YOU are so RIGHT!!!

**Comment by saxmydix** [comment]
@samikhawaja why don't you join us on telegram dude?

**Comment by p8tgames** [comment]
Join (at)RepublicOT for Help ;)

**Comment by saxmydix** [comment]
@Mi6PTrouble join this group on telegram.

**Comment by samikhawaja** [comment]
lol I have not been up to date on the NO U meme :).

Anyways I have got it building.

Cheers.
